x-common-volumes: &common-volumes
  - ~/.ccache:/ccache
  - ./build:/build
  - ../kernel-configs:/config
  - ./release:/release
  - ./patches:/patches
  - ./config.json:/usr/local/bin/config.json
  - ~/kernel-deb/:/gitrepo
  - ./.packagecloud:/root/.packagecloud

x-native-build: &native-build
  context: .
  args:
    TARGET_ARCH: ${TARGET_ARCH:-x86_64}
    CROSS_COMPILE_PREFIX: ${CROSS_COMPILE_PREFIX:-}

x-cross-build: &cross-build
  context: .
  args:
    TARGET_ARCH: ${CROSS_TARGET_ARCH:-arm64}
    CROSS_COMPILE_PREFIX: ${CROSS_COMPILE_PREFIX:-aarch64-linux-gnu-}

services:
  kernel-builder:
    build: *native-build
    container_name: kernel-builder
    volumes: *common-volumes
    environment:
      - TZ=Europe/Vienna
      - ARCH=${TARGET_ARCH:-x86_64}
      - CROSS_COMPILE=${CROSS_COMPILE_PREFIX:-}
    stdin_open: true
    tty: true

  shell:
    build: *native-build
    container_name: shell
    volumes: *common-volumes
    environment:
      - TZ=Europe/Vienna
    stdin_open: true
    tty: true
    entrypoint: /bin/bash

  kernel-builder-cross:
    build: *cross-build
    container_name: kernel-builder-cross
    volumes: *common-volumes
    environment:
      - TZ=Europe/Vienna
      - ARCH=${CROSS_TARGET_ARCH:-arm64}
      - CROSS_COMPILE=${CROSS_COMPILE_PREFIX:-aarch64-linux-gnu-}
    stdin_open: true
    tty: true

  shell-cross:
    build: *cross-build
    container_name: cross-shell
    volumes: *common-volumes
    environment:
      - TZ=Europe/Vienna
    stdin_open: true
    tty: true
    entrypoint: /bin/bash